### ISSUE TITLE
Managing History?

### ISSUE THREAD

**Issue by srivatsapraveen** [sucom/SPA.js#14]
How can we ensure that the SPA app continues to use the HistoryAPi so that the browser back/front buttons continue to work? It does not seem to happen by default. Under the Routes section, there are options to disable the browser buttons, but did not find anything to ensure that the browser navigation continues to work.

**Comment by sucom** [comment]
Hi,

In SPA.js, at core, the routes are triggered based on [data-spa-route] attribute. NOT based on URL address change. So, display of those routes in the address bar is optional. I understand your doubt, because other frameworks rely on history.pushState which intern triggers the route. But SPA.js, history is used for address bar "display purpose only". otherwise, routes are functional by default using necessary event calls based on [data-spa-route].

Hope it helps.

Thanks,
